version: '3'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres1
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=insurance

  web:
    build: .
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - postgres

